### ISSUE TITLE
Puppet.initialize_settings call needed in query.rb for face to work from Ruby script

### ISSUE THREAD

**Issue by legooolas** [dalen/puppet-puppetdbquery#31]
When attempting to use the query face from a simple ruby script, e.g. 

```ruby
require 'puppet/face'
print Puppet::Face[:query, "1"].nodes('(manufacturer="Dell Inc.")').join ", "
```

... I get an error as follows:

```
/usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1292:in `convert': Error converting value for param 'localcacert': Error converting value for param 'certdir': Error converting value for param 'ssldir': Could not find value for $confdir (Puppet::Settings::InterpolationError)
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `gsub'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `convert'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1264:in `interpolate'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1289:in `convert'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `gsub'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `convert'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1264:in `interpolate'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1289:in `convert'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `gsub'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1283:in `convert'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1264:in `interpolate'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:1029:in `value'
	from /usr/lib/ruby/site_ruby/1.8/puppet/settings.rb:118:in `[]'
	from /usr/lib/ruby/site_ruby/1.8/puppet.rb:70:in `[]'
	from /usr/lib/ruby/site_ruby/1.8/puppet/ssl/validator/default_validator.rb:22:in `initialize'
	from /usr/lib/ruby/site_ruby/1.8/puppet/ssl/validator.rb:27:in `new'
	from /usr/lib/ruby/site_ruby/1.8/puppet/ssl/validator.rb:27:in `default_validator'
	from /usr/lib/ruby/site_ruby/1.8/puppet/network/http_pool.rb:36:in `http_instance'
	from /etc/puppet/modules/puppetdbquery/lib/puppetdb/connection.rb:59:in `query'
	from /etc/puppet/modules/puppetdbquery/lib/puppet/face/query.rb:70:in `nodes implementation, required on Ruby 1.8'
	from /usr/lib/ruby/site_ruby/1.8/puppet/interface/action.rb+eval[wrapper]:242:in `__send__'
	from /usr/lib/ruby/site_ruby/1.8/puppet/interface/action.rb+eval[wrapper]:242:in `nodes'
	from ./test-query.rb:23
```

I believe this is due to a missing `Puppet.initialize_settings` call in query.rb.

I'll make a pull request shortly with this minor change included.

  Cheers!

**Comment by dalen** [comment]
I've added the initialize_settings call to the ruby API usage instructions in the README now instead. Can't do it automatically as someone else might already have initialized the settings and then we don't want to reset them. This is basically a bit of a fundamental issue with the faces API in Puppet.
