### ISSUE TITLE
support for 3.8.1

### ISSUE THREAD

**Issue by evilbofh** [dalen/puppet-puppetdbquery#80]
Since upgrading to pe-puppet 3.8.1 I get the following errors with manifests that include query calls

2015-12-11 11:21:12,918 ERROR [puppet-server] Puppet undefined method `server_urls' for #<Puppet::Util::Puppetdb::Config:0x3e3886a> at /etc/puppetlabs/puppe
t/environments/prd/current/puppet/application/nagioscore/manifests/params.pp:7 on node apddcungp002.apac.aon.bz
2015-12-11 11:21:12,929 ERROR [puppet-server] Puppet undefined method `server_urls' for #<Puppet::Util::Puppetdb::Config:0x3e3886a> at /etc/puppetlabs/puppe
t/environments/prd/current/puppet/application/nagioscore/manifests/params.pp:7 on node apddcungp002.apac.aon.bz
/var/opt/lib/pe-puppet-server/jruby-gems/gems/ruby-puppetdb-2.1.0/lib/puppet/parser/functions/query_nodes.rb:28:in `real_function_query_nodes'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/functions.rb:164:in `function_query_nodes'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/profiler/around_profiler.rb:58:in `profile'

**Comment by dalen** [comment]
Hi, you likely have PuppetDB 2.x installed. So then you need puppetdbquery 1.x instead of 2.x. So if you downgrade it should work.
